// Code generated by protoc-gen-go. DO NOT EDIT.
// source: query.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type QueryOptions_FilterType int32

const (
	QueryOptions_NO_FILTER  QueryOptions_FilterType = 0
	QueryOptions_HIDE_OLDER QueryOptions_FilterType = 1
)

var QueryOptions_FilterType_name = map[int32]string{
	0: "NO_FILTER",
	1: "HIDE_OLDER",
}

var QueryOptions_FilterType_value = map[string]int32{
	"NO_FILTER":  0,
	"HIDE_OLDER": 1,
}

func (x QueryOptions_FilterType) String() string {
	return proto.EnumName(QueryOptions_FilterType_name, int32(x))
}

func (QueryOptions_FilterType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{0, 0}
}

type Query_Type int32

const (
	Query_THREAD_SNAPSHOTS Query_Type = 0
	Query_CONTACTS         Query_Type = 1
)

var Query_Type_name = map[int32]string{
	0: "THREAD_SNAPSHOTS",
	1: "CONTACTS",
}

var Query_Type_value = map[string]int32{
	"THREAD_SNAPSHOTS": 0,
	"CONTACTS":         1,
}

func (x Query_Type) String() string {
	return proto.EnumName(Query_Type_name, int32(x))
}

func (Query_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{1, 0}
}

type PubSubQuery_ResponseType int32

const (
	PubSubQuery_P2P    PubSubQuery_ResponseType = 0
	PubSubQuery_PUBSUB PubSubQuery_ResponseType = 1
)

var PubSubQuery_ResponseType_name = map[int32]string{
	0: "P2P",
	1: "PUBSUB",
}

var PubSubQuery_ResponseType_value = map[string]int32{
	"P2P":    0,
	"PUBSUB": 1,
}

func (x PubSubQuery_ResponseType) String() string {
	return proto.EnumName(PubSubQuery_ResponseType_name, int32(x))
}

func (PubSubQuery_ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{2, 0}
}

type QueryOptions struct {
	LocalOnly            bool                    `protobuf:"varint,1,opt,name=localOnly,proto3" json:"localOnly,omitempty"`
	RemoteOnly           bool                    `protobuf:"varint,6,opt,name=remoteOnly,proto3" json:"remoteOnly,omitempty"`
	Limit                int32                   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Wait                 int32                   `protobuf:"varint,3,opt,name=wait,proto3" json:"wait,omitempty"`
	Filter               QueryOptions_FilterType `protobuf:"varint,4,opt,name=filter,proto3,enum=QueryOptions_FilterType" json:"filter,omitempty"`
	Exclude              []string                `protobuf:"bytes,5,rep,name=exclude,proto3" json:"exclude,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *QueryOptions) Reset()         { *m = QueryOptions{} }
func (m *QueryOptions) String() string { return proto.CompactTextString(m) }
func (*QueryOptions) ProtoMessage()    {}
func (*QueryOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{0}
}

func (m *QueryOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryOptions.Unmarshal(m, b)
}
func (m *QueryOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryOptions.Marshal(b, m, deterministic)
}
func (m *QueryOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOptions.Merge(m, src)
}
func (m *QueryOptions) XXX_Size() int {
	return xxx_messageInfo_QueryOptions.Size(m)
}
func (m *QueryOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOptions.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOptions proto.InternalMessageInfo

func (m *QueryOptions) GetLocalOnly() bool {
	if m != nil {
		return m.LocalOnly
	}
	return false
}

func (m *QueryOptions) GetRemoteOnly() bool {
	if m != nil {
		return m.RemoteOnly
	}
	return false
}

func (m *QueryOptions) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryOptions) GetWait() int32 {
	if m != nil {
		return m.Wait
	}
	return 0
}

func (m *QueryOptions) GetFilter() QueryOptions_FilterType {
	if m != nil {
		return m.Filter
	}
	return QueryOptions_NO_FILTER
}

func (m *QueryOptions) GetExclude() []string {
	if m != nil {
		return m.Exclude
	}
	return nil
}

type Query struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string        `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Type                 Query_Type    `protobuf:"varint,3,opt,name=type,proto3,enum=Query_Type" json:"type,omitempty"`
	Options              *QueryOptions `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	Payload              *any.Any      `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{1}
}

func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Query) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Query) GetType() Query_Type {
	if m != nil {
		return m.Type
	}
	return Query_THREAD_SNAPSHOTS
}

func (m *Query) GetOptions() *QueryOptions {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *Query) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type PubSubQuery struct {
	Id                   string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 Query_Type               `protobuf:"varint,2,opt,name=type,proto3,enum=Query_Type" json:"type,omitempty"`
	Payload              *any.Any                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ResponseType         PubSubQuery_ResponseType `protobuf:"varint,4,opt,name=responseType,proto3,enum=PubSubQuery_ResponseType" json:"responseType,omitempty"`
	Exclude              []string                 `protobuf:"bytes,5,rep,name=exclude,proto3" json:"exclude,omitempty"`
	Topic                string                   `protobuf:"bytes,6,opt,name=topic,proto3" json:"topic,omitempty"`
	Timeout              int32                    `protobuf:"varint,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PubSubQuery) Reset()         { *m = PubSubQuery{} }
func (m *PubSubQuery) String() string { return proto.CompactTextString(m) }
func (*PubSubQuery) ProtoMessage()    {}
func (*PubSubQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{2}
}

func (m *PubSubQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubSubQuery.Unmarshal(m, b)
}
func (m *PubSubQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubSubQuery.Marshal(b, m, deterministic)
}
func (m *PubSubQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubSubQuery.Merge(m, src)
}
func (m *PubSubQuery) XXX_Size() int {
	return xxx_messageInfo_PubSubQuery.Size(m)
}
func (m *PubSubQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PubSubQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PubSubQuery proto.InternalMessageInfo

func (m *PubSubQuery) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PubSubQuery) GetType() Query_Type {
	if m != nil {
		return m.Type
	}
	return Query_THREAD_SNAPSHOTS
}

func (m *PubSubQuery) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *PubSubQuery) GetResponseType() PubSubQuery_ResponseType {
	if m != nil {
		return m.ResponseType
	}
	return PubSubQuery_P2P
}

func (m *PubSubQuery) GetExclude() []string {
	if m != nil {
		return m.Exclude
	}
	return nil
}

func (m *PubSubQuery) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *PubSubQuery) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

type QueryResult struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Local                bool                 `protobuf:"varint,3,opt,name=local,proto3" json:"local,omitempty"`
	Value                *any.Any             `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *QueryResult) Reset()         { *m = QueryResult{} }
func (m *QueryResult) String() string { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()    {}
func (*QueryResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{3}
}

func (m *QueryResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResult.Unmarshal(m, b)
}
func (m *QueryResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResult.Marshal(b, m, deterministic)
}
func (m *QueryResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResult.Merge(m, src)
}
func (m *QueryResult) XXX_Size() int {
	return xxx_messageInfo_QueryResult.Size(m)
}
func (m *QueryResult) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResult.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResult proto.InternalMessageInfo

func (m *QueryResult) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueryResult) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *QueryResult) GetLocal() bool {
	if m != nil {
		return m.Local
	}
	return false
}

func (m *QueryResult) GetValue() *any.Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type QueryResults struct {
	Type                 Query_Type     `protobuf:"varint,1,opt,name=type,proto3,enum=Query_Type" json:"type,omitempty"`
	Items                []*QueryResult `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *QueryResults) Reset()         { *m = QueryResults{} }
func (m *QueryResults) String() string { return proto.CompactTextString(m) }
func (*QueryResults) ProtoMessage()    {}
func (*QueryResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{4}
}

func (m *QueryResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryResults.Unmarshal(m, b)
}
func (m *QueryResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryResults.Marshal(b, m, deterministic)
}
func (m *QueryResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResults.Merge(m, src)
}
func (m *QueryResults) XXX_Size() int {
	return xxx_messageInfo_QueryResults.Size(m)
}
func (m *QueryResults) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResults.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResults proto.InternalMessageInfo

func (m *QueryResults) GetType() Query_Type {
	if m != nil {
		return m.Type
	}
	return Query_THREAD_SNAPSHOTS
}

func (m *QueryResults) GetItems() []*QueryResult {
	if m != nil {
		return m.Items
	}
	return nil
}

type PubSubQueryResults struct {
	Id                   string        `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Results              *QueryResults `protobuf:"bytes,2,opt,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PubSubQueryResults) Reset()         { *m = PubSubQueryResults{} }
func (m *PubSubQueryResults) String() string { return proto.CompactTextString(m) }
func (*PubSubQueryResults) ProtoMessage()    {}
func (*PubSubQueryResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{5}
}

func (m *PubSubQueryResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PubSubQueryResults.Unmarshal(m, b)
}
func (m *PubSubQueryResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PubSubQueryResults.Marshal(b, m, deterministic)
}
func (m *PubSubQueryResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PubSubQueryResults.Merge(m, src)
}
func (m *PubSubQueryResults) XXX_Size() int {
	return xxx_messageInfo_PubSubQueryResults.Size(m)
}
func (m *PubSubQueryResults) XXX_DiscardUnknown() {
	xxx_messageInfo_PubSubQueryResults.DiscardUnknown(m)
}

var xxx_messageInfo_PubSubQueryResults proto.InternalMessageInfo

func (m *PubSubQueryResults) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PubSubQueryResults) GetResults() *QueryResults {
	if m != nil {
		return m.Results
	}
	return nil
}

type ContactQuery struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactQuery) Reset()         { *m = ContactQuery{} }
func (m *ContactQuery) String() string { return proto.CompactTextString(m) }
func (*ContactQuery) ProtoMessage()    {}
func (*ContactQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{6}
}

func (m *ContactQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactQuery.Unmarshal(m, b)
}
func (m *ContactQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactQuery.Marshal(b, m, deterministic)
}
func (m *ContactQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactQuery.Merge(m, src)
}
func (m *ContactQuery) XXX_Size() int {
	return xxx_messageInfo_ContactQuery.Size(m)
}
func (m *ContactQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ContactQuery proto.InternalMessageInfo

func (m *ContactQuery) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ContactQuery) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ThreadSnapshotQuery struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadSnapshotQuery) Reset()         { *m = ThreadSnapshotQuery{} }
func (m *ThreadSnapshotQuery) String() string { return proto.CompactTextString(m) }
func (*ThreadSnapshotQuery) ProtoMessage()    {}
func (*ThreadSnapshotQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c6ac9b241082464, []int{7}
}

func (m *ThreadSnapshotQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadSnapshotQuery.Unmarshal(m, b)
}
func (m *ThreadSnapshotQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadSnapshotQuery.Marshal(b, m, deterministic)
}
func (m *ThreadSnapshotQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadSnapshotQuery.Merge(m, src)
}
func (m *ThreadSnapshotQuery) XXX_Size() int {
	return xxx_messageInfo_ThreadSnapshotQuery.Size(m)
}
func (m *ThreadSnapshotQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadSnapshotQuery.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadSnapshotQuery proto.InternalMessageInfo

func (m *ThreadSnapshotQuery) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto.RegisterEnum("QueryOptions_FilterType", QueryOptions_FilterType_name, QueryOptions_FilterType_value)
	proto.RegisterEnum("Query_Type", Query_Type_name, Query_Type_value)
	proto.RegisterEnum("PubSubQuery_ResponseType", PubSubQuery_ResponseType_name, PubSubQuery_ResponseType_value)
	proto.RegisterType((*QueryOptions)(nil), "QueryOptions")
	proto.RegisterType((*Query)(nil), "Query")
	proto.RegisterType((*PubSubQuery)(nil), "PubSubQuery")
	proto.RegisterType((*QueryResult)(nil), "QueryResult")
	proto.RegisterType((*QueryResults)(nil), "QueryResults")
	proto.RegisterType((*PubSubQueryResults)(nil), "PubSubQueryResults")
	proto.RegisterType((*ContactQuery)(nil), "ContactQuery")
	proto.RegisterType((*ThreadSnapshotQuery)(nil), "ThreadSnapshotQuery")
}

func init() { proto.RegisterFile("query.proto", fileDescriptor_5c6ac9b241082464) }

var fileDescriptor_5c6ac9b241082464 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x4e, 0xdb, 0x4c,
	0x14, 0xc5, 0x49, 0x1c, 0x93, 0xeb, 0x24, 0xb2, 0xe6, 0x63, 0x61, 0xd0, 0x27, 0x88, 0xfc, 0x2d,
	0x88, 0xf8, 0xd4, 0x49, 0x95, 0x6e, 0xdb, 0x45, 0x80, 0x20, 0x90, 0x28, 0x49, 0xc7, 0x66, 0xd3,
	0x0d, 0x9a, 0xc4, 0x03, 0x8c, 0xea, 0x78, 0x5c, 0x7b, 0xdc, 0x92, 0xa7, 0xe8, 0x0b, 0xf4, 0xad,
	0xfa, 0x20, 0x7d, 0x85, 0xca, 0x33, 0x76, 0x31, 0x7f, 0x6a, 0x77, 0xb9, 0x73, 0x4e, 0xae, 0xcf,
	0xb9, 0xe7, 0x5e, 0xb0, 0x3f, 0xe7, 0x2c, 0x5d, 0xe3, 0x24, 0x15, 0x52, 0xec, 0x6c, 0xdf, 0x08,
	0x71, 0x13, 0xb1, 0x91, 0xaa, 0x16, 0xf9, 0xf5, 0x88, 0xc6, 0x15, 0xb4, 0xf7, 0x18, 0x92, 0x7c,
	0xc5, 0x32, 0x49, 0x57, 0x89, 0x26, 0x78, 0x3f, 0x0d, 0xe8, 0x7e, 0x28, 0x7a, 0xcd, 0x12, 0xc9,
	0x45, 0x9c, 0xa1, 0x7f, 0xa1, 0x13, 0x89, 0x25, 0x8d, 0x66, 0x71, 0xb4, 0x76, 0x8d, 0x81, 0x31,
	0xdc, 0x24, 0xf7, 0x0f, 0x68, 0x17, 0x20, 0x65, 0x2b, 0x21, 0x99, 0x82, 0xdb, 0x0a, 0xae, 0xbd,
	0xa0, 0x2d, 0x30, 0x23, 0xbe, 0xe2, 0xd2, 0x6d, 0x0c, 0x8c, 0xa1, 0x49, 0x74, 0x81, 0x10, 0xb4,
	0xbe, 0x52, 0x2e, 0xdd, 0xa6, 0x7a, 0x54, 0xbf, 0xd1, 0x6b, 0x68, 0x5f, 0xf3, 0x48, 0xb2, 0xd4,
	0x6d, 0x0d, 0x8c, 0x61, 0x7f, 0xec, 0xe2, 0xba, 0x0c, 0x7c, 0xa2, 0xb0, 0x60, 0x9d, 0x30, 0x52,
	0xf2, 0x90, 0x0b, 0x16, 0xbb, 0x5b, 0x46, 0x79, 0xc8, 0x5c, 0x73, 0xd0, 0x1c, 0x76, 0x48, 0x55,
	0x7a, 0xff, 0x03, 0xdc, 0xf3, 0x51, 0x0f, 0x3a, 0x17, 0xb3, 0xab, 0x93, 0xb3, 0xf3, 0x60, 0x4a,
	0x9c, 0x0d, 0xd4, 0x07, 0x38, 0x3d, 0x3b, 0x9e, 0x5e, 0xcd, 0xce, 0x8f, 0xa7, 0xc4, 0x31, 0xbc,
	0x1f, 0x06, 0x98, 0xea, 0x53, 0xa8, 0x0f, 0x0d, 0x1e, 0x2a, 0x8f, 0x1d, 0xd2, 0xe0, 0x61, 0x21,
	0x5e, 0x8a, 0x4f, 0x2c, 0x56, 0xe2, 0x3b, 0x44, 0x17, 0x68, 0x0f, 0x5a, 0x72, 0x9d, 0x30, 0x25,
	0xbe, 0x3f, 0xb6, 0xb5, 0x4c, 0xac, 0x94, 0x29, 0x00, 0xed, 0x83, 0x25, 0xb4, 0x6a, 0x65, 0xc5,
	0x1e, 0xf7, 0x1e, 0x58, 0x21, 0x15, 0x8a, 0x30, 0x58, 0x09, 0x5d, 0x47, 0x82, 0x86, 0xae, 0xa9,
	0x88, 0x5b, 0x58, 0xc7, 0x83, 0xab, 0x78, 0xf0, 0x24, 0x5e, 0x93, 0x8a, 0xe4, 0x1d, 0x40, 0x4b,
	0x19, 0xda, 0x02, 0x27, 0x38, 0x25, 0xd3, 0xc9, 0xf1, 0x95, 0x7f, 0x31, 0x99, 0xfb, 0xa7, 0xb3,
	0xc0, 0x77, 0x36, 0x50, 0x17, 0x36, 0x8f, 0x66, 0x17, 0xc1, 0xe4, 0x28, 0xf0, 0x1d, 0xc3, 0xfb,
	0xde, 0x00, 0x7b, 0x9e, 0x2f, 0xfc, 0x7c, 0xf1, 0xbc, 0xb7, 0xca, 0x45, 0xe3, 0x25, 0x17, 0x35,
	0x71, 0xcd, 0xbf, 0x10, 0x87, 0xde, 0x41, 0x37, 0x65, 0x59, 0x22, 0xe2, 0x8c, 0x15, 0x5d, 0xca,
	0x14, 0xb7, 0x71, 0x4d, 0x04, 0x26, 0x35, 0x02, 0x79, 0x40, 0x7f, 0x39, 0x4c, 0x9d, 0x42, 0xc2,
	0x97, 0x6a, 0xbb, 0x54, 0x0a, 0x09, 0x5f, 0x16, 0xfc, 0x62, 0x75, 0x45, 0x2e, 0x5d, 0x4b, 0x6d,
	0x51, 0x55, 0x7a, 0xff, 0x41, 0xb7, 0xfe, 0x1d, 0x64, 0x41, 0x73, 0x3e, 0x9e, 0x3b, 0x1b, 0x08,
	0xa0, 0x3d, 0xbf, 0x3c, 0xf4, 0x2f, 0x0f, 0x1d, 0xc3, 0xfb, 0x66, 0x80, 0xad, 0x34, 0x11, 0x96,
	0xe5, 0x91, 0x7c, 0x32, 0x1e, 0x0c, 0xad, 0x90, 0x4a, 0x3d, 0x1e, 0x7b, 0xbc, 0xf3, 0xc4, 0x7a,
	0x50, 0x9d, 0x0d, 0x51, 0x3c, 0xb5, 0xe7, 0xc5, 0x51, 0xa8, 0x59, 0x6d, 0x12, 0x5d, 0xa0, 0x03,
	0x30, 0xbf, 0xd0, 0x28, 0x67, 0xe5, 0x1e, 0x3c, 0x3f, 0x41, 0x4d, 0xf1, 0xfc, 0xf2, 0xee, 0xb4,
	0xa0, 0xec, 0x77, 0x40, 0xc6, 0x4b, 0x01, 0x79, 0x60, 0x72, 0xc9, 0x56, 0x99, 0xdb, 0x18, 0x34,
	0x87, 0xf6, 0xb8, 0x8b, 0x6b, 0x7f, 0x27, 0x1a, 0xf2, 0xde, 0x03, 0xaa, 0xcd, 0xbf, 0x6a, 0xfd,
	0xd8, 0xec, 0x3e, 0x58, 0xa9, 0x86, 0x4a, 0xbf, 0xbd, 0x7a, 0xaf, 0x8c, 0x54, 0xa8, 0xf7, 0x16,
	0xba, 0x47, 0x22, 0x96, 0x74, 0x29, 0xf5, 0x52, 0xb9, 0x60, 0xd1, 0x30, 0x4c, 0x59, 0x96, 0x95,
	0xdd, 0xaa, 0xb2, 0xb8, 0xf0, 0x98, 0xae, 0x58, 0x79, 0x39, 0xea, 0xb7, 0x37, 0x82, 0x7f, 0x82,
	0xdb, 0x94, 0xd1, 0xd0, 0x8f, 0x69, 0x92, 0xdd, 0x8a, 0x3f, 0x35, 0x39, 0xdc, 0x85, 0x1e, 0x17,
	0x58, 0xb2, 0x3b, 0xc9, 0x8b, 0xa1, 0x2d, 0x3e, 0xf6, 0x6e, 0xc4, 0xab, 0xb2, 0x1c, 0x25, 0x8b,
	0x45, 0x5b, 0xcd, 0xf1, 0xcd, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x95, 0xd9, 0x6b, 0xfd,
	0x04, 0x00, 0x00,
}
