// Code generated by protoc-gen-go. DO NOT EDIT.
// source: threads_service.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// for wire transport
type ThreadEnvelope struct {
	Thread               string   `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	Hash                 string   `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`             // Deprecated: Do not use.
	Ciphertext           []byte   `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"` // Deprecated: Do not use.
	Sig                  []byte   `protobuf:"bytes,4,opt,name=sig,proto3" json:"sig,omitempty"`
	Node                 []byte   `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	Block                []byte   `protobuf:"bytes,6,opt,name=block,proto3" json:"block,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadEnvelope) Reset()         { *m = ThreadEnvelope{} }
func (m *ThreadEnvelope) String() string { return proto.CompactTextString(m) }
func (*ThreadEnvelope) ProtoMessage()    {}
func (*ThreadEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f4f9ff5658127, []int{0}
}

func (m *ThreadEnvelope) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadEnvelope.Unmarshal(m, b)
}
func (m *ThreadEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadEnvelope.Marshal(b, m, deterministic)
}
func (m *ThreadEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadEnvelope.Merge(m, src)
}
func (m *ThreadEnvelope) XXX_Size() int {
	return xxx_messageInfo_ThreadEnvelope.Size(m)
}
func (m *ThreadEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadEnvelope proto.InternalMessageInfo

func (m *ThreadEnvelope) GetThread() string {
	if m != nil {
		return m.Thread
	}
	return ""
}

// Deprecated: Do not use.
func (m *ThreadEnvelope) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// Deprecated: Do not use.
func (m *ThreadEnvelope) GetCiphertext() []byte {
	if m != nil {
		return m.Ciphertext
	}
	return nil
}

func (m *ThreadEnvelope) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

func (m *ThreadEnvelope) GetNode() []byte {
	if m != nil {
		return m.Node
	}
	return nil
}

func (m *ThreadEnvelope) GetBlock() []byte {
	if m != nil {
		return m.Block
	}
	return nil
}

type ThreadEnvelopeAck struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadEnvelopeAck) Reset()         { *m = ThreadEnvelopeAck{} }
func (m *ThreadEnvelopeAck) String() string { return proto.CompactTextString(m) }
func (*ThreadEnvelopeAck) ProtoMessage()    {}
func (*ThreadEnvelopeAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f4f9ff5658127, []int{1}
}

func (m *ThreadEnvelopeAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadEnvelopeAck.Unmarshal(m, b)
}
func (m *ThreadEnvelopeAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadEnvelopeAck.Marshal(b, m, deterministic)
}
func (m *ThreadEnvelopeAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadEnvelopeAck.Merge(m, src)
}
func (m *ThreadEnvelopeAck) XXX_Size() int {
	return xxx_messageInfo_ThreadEnvelopeAck.Size(m)
}
func (m *ThreadEnvelopeAck) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadEnvelopeAck.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadEnvelopeAck proto.InternalMessageInfo

func (m *ThreadEnvelopeAck) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ThreadBlock struct {
	Header               *ThreadBlockHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Type                 Block_BlockType    `protobuf:"varint,2,opt,name=type,proto3,enum=Block_BlockType" json:"type,omitempty"`
	Payload              *any.Any           `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ThreadBlock) Reset()         { *m = ThreadBlock{} }
func (m *ThreadBlock) String() string { return proto.CompactTextString(m) }
func (*ThreadBlock) ProtoMessage()    {}
func (*ThreadBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f4f9ff5658127, []int{2}
}

func (m *ThreadBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadBlock.Unmarshal(m, b)
}
func (m *ThreadBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadBlock.Marshal(b, m, deterministic)
}
func (m *ThreadBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadBlock.Merge(m, src)
}
func (m *ThreadBlock) XXX_Size() int {
	return xxx_messageInfo_ThreadBlock.Size(m)
}
func (m *ThreadBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadBlock.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadBlock proto.InternalMessageInfo

func (m *ThreadBlock) GetHeader() *ThreadBlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *ThreadBlock) GetType() Block_BlockType {
	if m != nil {
		return m.Type
	}
	return Block_MERGE
}

func (m *ThreadBlock) GetPayload() *any.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

type ThreadBlockHeader struct {
	Date                 *timestamp.Timestamp `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Parents              []string             `protobuf:"bytes,2,rep,name=parents,proto3" json:"parents,omitempty"` // Deprecated: Do not use.
	Author               string               `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Address              string               `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ThreadBlockHeader) Reset()         { *m = ThreadBlockHeader{} }
func (m *ThreadBlockHeader) String() string { return proto.CompactTextString(m) }
func (*ThreadBlockHeader) ProtoMessage()    {}
func (*ThreadBlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f4f9ff5658127, []int{3}
}

func (m *ThreadBlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadBlockHeader.Unmarshal(m, b)
}
func (m *ThreadBlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadBlockHeader.Marshal(b, m, deterministic)
}
func (m *ThreadBlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadBlockHeader.Merge(m, src)
}
func (m *ThreadBlockHeader) XXX_Size() int {
	return xxx_messageInfo_ThreadBlockHeader.Size(m)
}
func (m *ThreadBlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadBlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadBlockHeader proto.InternalMessageInfo

func (m *ThreadBlockHeader) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

// Deprecated: Do not use.
func (m *ThreadBlockHeader) GetParents() []string {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *ThreadBlockHeader) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *ThreadBlockHeader) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ThreadAdd struct {
	Inviter              *Peer    `protobuf:"bytes,1,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Thread               *Thread  `protobuf:"bytes,2,opt,name=thread,proto3" json:"thread,omitempty"`
	Invitee              string   `protobuf:"bytes,3,opt,name=invitee,proto3" json:"invitee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadAdd) Reset()         { *m = ThreadAdd{} }
func (m *ThreadAdd) String() string { return proto.CompactTextString(m) }
func (*ThreadAdd) ProtoMessage()    {}
func (*ThreadAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f4f9ff5658127, []int{4}
}

func (m *ThreadAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadAdd.Unmarshal(m, b)
}
func (m *ThreadAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadAdd.Marshal(b, m, deterministic)
}
func (m *ThreadAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadAdd.Merge(m, src)
}
func (m *ThreadAdd) XXX_Size() int {
	return xxx_messageInfo_ThreadAdd.Size(m)
}
func (m *ThreadAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadAdd proto.InternalMessageInfo

func (m *ThreadAdd) GetInviter() *Peer {
	if m != nil {
		return m.Inviter
	}
	return nil
}

func (m *ThreadAdd) GetThread() *Thread {
	if m != nil {
		return m.Thread
	}
	return nil
}

func (m *ThreadAdd) GetInvitee() string {
	if m != nil {
		return m.Invitee
	}
	return ""
}

// Deprecated: Do not use.
type ThreadIgnore struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadIgnore) Reset()         { *m = ThreadIgnore{} }
func (m *ThreadIgnore) String() string { return proto.CompactTextString(m) }
func (*ThreadIgnore) ProtoMessage()    {}
func (*ThreadIgnore) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f4f9ff5658127, []int{5}
}

func (m *ThreadIgnore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadIgnore.Unmarshal(m, b)
}
func (m *ThreadIgnore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadIgnore.Marshal(b, m, deterministic)
}
func (m *ThreadIgnore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadIgnore.Merge(m, src)
}
func (m *ThreadIgnore) XXX_Size() int {
	return xxx_messageInfo_ThreadIgnore.Size(m)
}
func (m *ThreadIgnore) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadIgnore.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadIgnore proto.InternalMessageInfo

func (m *ThreadIgnore) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

// Deprecated: Do not use.
type ThreadFlag struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadFlag) Reset()         { *m = ThreadFlag{} }
func (m *ThreadFlag) String() string { return proto.CompactTextString(m) }
func (*ThreadFlag) ProtoMessage()    {}
func (*ThreadFlag) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f4f9ff5658127, []int{6}
}

func (m *ThreadFlag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadFlag.Unmarshal(m, b)
}
func (m *ThreadFlag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadFlag.Marshal(b, m, deterministic)
}
func (m *ThreadFlag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadFlag.Merge(m, src)
}
func (m *ThreadFlag) XXX_Size() int {
	return xxx_messageInfo_ThreadFlag.Size(m)
}
func (m *ThreadFlag) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadFlag.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadFlag proto.InternalMessageInfo

func (m *ThreadFlag) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type ThreadJoin struct {
	Inviter              string   `protobuf:"bytes,1,opt,name=inviter,proto3" json:"inviter,omitempty"`
	Peer                 *Peer    `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadJoin) Reset()         { *m = ThreadJoin{} }
func (m *ThreadJoin) String() string { return proto.CompactTextString(m) }
func (*ThreadJoin) ProtoMessage()    {}
func (*ThreadJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f4f9ff5658127, []int{7}
}

func (m *ThreadJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadJoin.Unmarshal(m, b)
}
func (m *ThreadJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadJoin.Marshal(b, m, deterministic)
}
func (m *ThreadJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadJoin.Merge(m, src)
}
func (m *ThreadJoin) XXX_Size() int {
	return xxx_messageInfo_ThreadJoin.Size(m)
}
func (m *ThreadJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadJoin.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadJoin proto.InternalMessageInfo

func (m *ThreadJoin) GetInviter() string {
	if m != nil {
		return m.Inviter
	}
	return ""
}

func (m *ThreadJoin) GetPeer() *Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

type ThreadAnnounce struct {
	Peer                 *Peer    `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadAnnounce) Reset()         { *m = ThreadAnnounce{} }
func (m *ThreadAnnounce) String() string { return proto.CompactTextString(m) }
func (*ThreadAnnounce) ProtoMessage()    {}
func (*ThreadAnnounce) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f4f9ff5658127, []int{8}
}

func (m *ThreadAnnounce) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadAnnounce.Unmarshal(m, b)
}
func (m *ThreadAnnounce) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadAnnounce.Marshal(b, m, deterministic)
}
func (m *ThreadAnnounce) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadAnnounce.Merge(m, src)
}
func (m *ThreadAnnounce) XXX_Size() int {
	return xxx_messageInfo_ThreadAnnounce.Size(m)
}
func (m *ThreadAnnounce) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadAnnounce.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadAnnounce proto.InternalMessageInfo

func (m *ThreadAnnounce) GetPeer() *Peer {
	if m != nil {
		return m.Peer
	}
	return nil
}

func (m *ThreadAnnounce) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ThreadMessage struct {
	Body                 string   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadMessage) Reset()         { *m = ThreadMessage{} }
func (m *ThreadMessage) String() string { return proto.CompactTextString(m) }
func (*ThreadMessage) ProtoMessage()    {}
func (*ThreadMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f4f9ff5658127, []int{9}
}

func (m *ThreadMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadMessage.Unmarshal(m, b)
}
func (m *ThreadMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadMessage.Marshal(b, m, deterministic)
}
func (m *ThreadMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadMessage.Merge(m, src)
}
func (m *ThreadMessage) XXX_Size() int {
	return xxx_messageInfo_ThreadMessage.Size(m)
}
func (m *ThreadMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadMessage proto.InternalMessageInfo

func (m *ThreadMessage) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type ThreadFiles struct {
	Target               string            `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"` // Deprecated: Do not use.
	Body                 string            `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Keys                 map[string]string `protobuf:"bytes,3,rep,name=keys,proto3" json:"keys,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ThreadFiles) Reset()         { *m = ThreadFiles{} }
func (m *ThreadFiles) String() string { return proto.CompactTextString(m) }
func (*ThreadFiles) ProtoMessage()    {}
func (*ThreadFiles) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f4f9ff5658127, []int{10}
}

func (m *ThreadFiles) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadFiles.Unmarshal(m, b)
}
func (m *ThreadFiles) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadFiles.Marshal(b, m, deterministic)
}
func (m *ThreadFiles) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadFiles.Merge(m, src)
}
func (m *ThreadFiles) XXX_Size() int {
	return xxx_messageInfo_ThreadFiles.Size(m)
}
func (m *ThreadFiles) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadFiles.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadFiles proto.InternalMessageInfo

// Deprecated: Do not use.
func (m *ThreadFiles) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ThreadFiles) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ThreadFiles) GetKeys() map[string]string {
	if m != nil {
		return m.Keys
	}
	return nil
}

// Deprecated: Do not use.
type ThreadComment struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Body                 string   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadComment) Reset()         { *m = ThreadComment{} }
func (m *ThreadComment) String() string { return proto.CompactTextString(m) }
func (*ThreadComment) ProtoMessage()    {}
func (*ThreadComment) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f4f9ff5658127, []int{11}
}

func (m *ThreadComment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadComment.Unmarshal(m, b)
}
func (m *ThreadComment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadComment.Marshal(b, m, deterministic)
}
func (m *ThreadComment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadComment.Merge(m, src)
}
func (m *ThreadComment) XXX_Size() int {
	return xxx_messageInfo_ThreadComment.Size(m)
}
func (m *ThreadComment) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadComment.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadComment proto.InternalMessageInfo

func (m *ThreadComment) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *ThreadComment) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

// Deprecated: Do not use.
type ThreadLike struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ThreadLike) Reset()         { *m = ThreadLike{} }
func (m *ThreadLike) String() string { return proto.CompactTextString(m) }
func (*ThreadLike) ProtoMessage()    {}
func (*ThreadLike) Descriptor() ([]byte, []int) {
	return fileDescriptor_402f4f9ff5658127, []int{12}
}

func (m *ThreadLike) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ThreadLike.Unmarshal(m, b)
}
func (m *ThreadLike) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ThreadLike.Marshal(b, m, deterministic)
}
func (m *ThreadLike) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ThreadLike.Merge(m, src)
}
func (m *ThreadLike) XXX_Size() int {
	return xxx_messageInfo_ThreadLike.Size(m)
}
func (m *ThreadLike) XXX_DiscardUnknown() {
	xxx_messageInfo_ThreadLike.DiscardUnknown(m)
}

var xxx_messageInfo_ThreadLike proto.InternalMessageInfo

func (m *ThreadLike) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func init() {
	proto.RegisterType((*ThreadEnvelope)(nil), "ThreadEnvelope")
	proto.RegisterType((*ThreadEnvelopeAck)(nil), "ThreadEnvelopeAck")
	proto.RegisterType((*ThreadBlock)(nil), "ThreadBlock")
	proto.RegisterType((*ThreadBlockHeader)(nil), "ThreadBlockHeader")
	proto.RegisterType((*ThreadAdd)(nil), "ThreadAdd")
	proto.RegisterType((*ThreadIgnore)(nil), "ThreadIgnore")
	proto.RegisterType((*ThreadFlag)(nil), "ThreadFlag")
	proto.RegisterType((*ThreadJoin)(nil), "ThreadJoin")
	proto.RegisterType((*ThreadAnnounce)(nil), "ThreadAnnounce")
	proto.RegisterType((*ThreadMessage)(nil), "ThreadMessage")
	proto.RegisterType((*ThreadFiles)(nil), "ThreadFiles")
	proto.RegisterMapType((map[string]string)(nil), "ThreadFiles.KeysEntry")
	proto.RegisterType((*ThreadComment)(nil), "ThreadComment")
	proto.RegisterType((*ThreadLike)(nil), "ThreadLike")
}

func init() { proto.RegisterFile("threads_service.proto", fileDescriptor_402f4f9ff5658127) }

var fileDescriptor_402f4f9ff5658127 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4d, 0x6b, 0xdb, 0x4c,
	0x10, 0x46, 0xb2, 0x62, 0xe3, 0x71, 0x12, 0xf2, 0x2e, 0x79, 0x83, 0x62, 0x4a, 0x63, 0x94, 0x1e,
	0x4c, 0xa0, 0x0a, 0xb8, 0x87, 0x96, 0x5c, 0x82, 0x53, 0x12, 0xfa, 0x09, 0x45, 0xe4, 0xd4, 0x4b,
	0x59, 0x5b, 0x53, 0x79, 0xb1, 0xbc, 0x2b, 0x76, 0xd7, 0xa6, 0xfa, 0x15, 0x3d, 0xf4, 0x0f, 0x94,
	0xfe, 0xd2, 0xa2, 0xfd, 0x50, 0x9c, 0xa6, 0xcd, 0x45, 0xcc, 0x33, 0xf3, 0xec, 0xce, 0x33, 0x1f,
	0x2b, 0xf8, 0x5f, 0x2f, 0x24, 0xd2, 0x5c, 0x7d, 0x51, 0x28, 0x37, 0x6c, 0x8e, 0x69, 0x25, 0x85,
	0x16, 0xc3, 0xe3, 0x42, 0x88, 0xa2, 0xc4, 0x73, 0x83, 0x66, 0xeb, 0xaf, 0xe7, 0x94, 0xd7, 0x2e,
	0x74, 0xf2, 0x67, 0x48, 0xb3, 0x15, 0x2a, 0x4d, 0x57, 0x95, 0x23, 0x0c, 0x56, 0x22, 0xc7, 0xd2,
	0x82, 0xe4, 0x67, 0x00, 0xfb, 0xb7, 0x26, 0xc5, 0x35, 0xdf, 0x60, 0x29, 0x2a, 0x24, 0x47, 0xd0,
	0xb5, 0x49, 0xe3, 0x60, 0x14, 0x8c, 0xfb, 0x99, 0x43, 0xe4, 0x08, 0xa2, 0x05, 0x55, 0x8b, 0x38,
	0x6c, 0xbc, 0x57, 0x61, 0x1c, 0x64, 0x06, 0x93, 0x04, 0x60, 0xce, 0xaa, 0x05, 0x4a, 0x8d, 0xdf,
	0x74, 0xdc, 0x19, 0x05, 0xe3, 0x5d, 0x13, 0xdd, 0xf2, 0x92, 0x03, 0xe8, 0x28, 0x56, 0xc4, 0x51,
	0x13, 0xcc, 0x1a, 0x93, 0x10, 0x88, 0xb8, 0xc8, 0x31, 0xde, 0x31, 0x2e, 0x63, 0x93, 0x43, 0xd8,
	0x99, 0x95, 0x62, 0xbe, 0x8c, 0xbb, 0xc6, 0x69, 0x41, 0x72, 0x0a, 0xff, 0xdd, 0x57, 0x38, 0x9d,
	0x2f, 0xc9, 0x3e, 0x84, 0xcc, 0x0b, 0x0c, 0x59, 0x9e, 0x7c, 0x0f, 0x60, 0x60, 0x59, 0x57, 0xcd,
	0x21, 0x72, 0x06, 0xdd, 0x05, 0xd2, 0x1c, 0xa5, 0xe1, 0x0c, 0x26, 0x24, 0xdd, 0x8a, 0xbe, 0x31,
	0x91, 0xcc, 0x31, 0xc8, 0x33, 0x88, 0x74, 0x5d, 0xa1, 0x29, 0x6c, 0x7f, 0x72, 0x90, 0x1a, 0x8e,
	0xfd, 0xde, 0xd6, 0x15, 0x66, 0x26, 0x4a, 0x52, 0xe8, 0x55, 0xb4, 0x2e, 0x05, 0xcd, 0x4d, 0x8d,
	0x83, 0xc9, 0x61, 0x6a, 0x3b, 0x9d, 0xfa, 0x4e, 0xa7, 0x53, 0x5e, 0x67, 0x9e, 0x94, 0xfc, 0x08,
	0xbc, 0xee, 0xad, 0x9c, 0x24, 0x85, 0x28, 0xa7, 0x1a, 0x9d, 0xaa, 0xe1, 0x83, 0x2b, 0x6e, 0xfd,
	0xb0, 0x32, 0xc3, 0x23, 0x4f, 0x9a, 0xac, 0x12, 0xb9, 0x56, 0x71, 0x38, 0xea, 0xb8, 0xbe, 0x7b,
	0x57, 0x33, 0x2a, 0xba, 0xd6, 0x0b, 0x21, 0x8d, 0xa4, 0x7e, 0xe6, 0x10, 0x89, 0xa1, 0x47, 0xf3,
	0x5c, 0xa2, 0x52, 0xa6, 0xe5, 0xfd, 0xcc, 0xc3, 0xa4, 0x80, 0xbe, 0x15, 0x35, 0xcd, 0x73, 0x72,
	0x02, 0x3d, 0xc6, 0x37, 0x4c, 0xb7, 0x5d, 0xda, 0x49, 0x3f, 0x21, 0xca, 0xcc, 0x7b, 0xc9, 0x49,
	0xbb, 0x0a, 0xa1, 0x89, 0xf7, 0x5c, 0x17, 0xdb, 0x9d, 0x88, 0xfd, 0x0d, 0xe8, 0x14, 0x78, 0x98,
	0x9c, 0xc1, 0xae, 0xe5, 0xbe, 0x2d, 0xb8, 0x90, 0x76, 0xab, 0xa8, 0x2c, 0x50, 0xb7, 0x5b, 0x65,
	0xd0, 0x45, 0x18, 0x07, 0xc9, 0x18, 0xc0, 0x72, 0x6f, 0x4a, 0x5a, 0x3c, 0xca, 0x9c, 0x7a, 0xe6,
	0x3b, 0xc1, 0xf8, 0x5d, 0x76, 0xe9, 0xa8, 0xad, 0xf0, 0x63, 0x88, 0x2a, 0x44, 0xe9, 0x64, 0xbb,
	0xb2, 0x8c, 0x2b, 0xb9, 0xf4, 0x0b, 0x3f, 0xe5, 0x5c, 0xac, 0xf9, 0x1c, 0x5b, 0x72, 0xf0, 0x80,
	0x6c, 0xb6, 0x94, 0xae, 0xec, 0x6a, 0xf4, 0x33, 0x63, 0x27, 0xa7, 0xb0, 0x67, 0x2f, 0xf8, 0x88,
	0x4a, 0xd1, 0x02, 0x1b, 0xd2, 0x4c, 0xe4, 0xb5, 0xd3, 0x60, 0xec, 0xe4, 0x57, 0xbb, 0x8f, 0x37,
	0xac, 0x44, 0x45, 0x86, 0xf7, 0x8b, 0x32, 0x63, 0x74, 0x9e, 0xf6, 0x7c, 0x78, 0x77, 0x9e, 0x9c,
	0x41, 0xb4, 0xc4, 0x5a, 0xc5, 0x9d, 0x51, 0x67, 0x3c, 0x98, 0x1c, 0xa5, 0x5b, 0x77, 0xa5, 0xef,
	0xb1, 0x56, 0xd7, 0x5c, 0xcb, 0x3a, 0x33, 0x9c, 0xe1, 0x4b, 0xe8, 0xb7, 0xae, 0xe6, 0xa5, 0x2d,
	0xd1, 0x6b, 0x69, 0xcc, 0xe6, 0x55, 0x6d, 0x68, 0xb9, 0xf6, 0x45, 0x58, 0x70, 0x11, 0xbe, 0x0a,
	0x92, 0x4b, 0x5f, 0xc9, 0x6b, 0xb1, 0x5a, 0x21, 0xd7, 0xff, 0x6a, 0xfd, 0xdf, 0x14, 0xde, 0x1f,
	0xdc, 0x07, 0xb6, 0x7c, 0x74, 0xc4, 0x57, 0x4f, 0x61, 0x8f, 0x89, 0xb4, 0xf9, 0x17, 0xb0, 0x66,
	0xdd, 0x67, 0x9f, 0xf7, 0x0a, 0xf1, 0xdc, 0xc1, 0xf3, 0x6a, 0x36, 0xeb, 0x9a, 0x17, 0xf0, 0xe2,
	0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xab, 0xdd, 0x07, 0xf0, 0x04, 0x00, 0x00,
}
